### ISSUE TITLE
Corne with mikoto@7.1 doesn't seem to support the MAX17048 fuel gauge

### ISSUE THREAD

**Issue by sebkinne** [keebd/zmk-firmware#1]
Hey Keebd team,

I snagged a Mikito from you the other day and got ZMK running on my corne without issues using these build files - with the exception of the battery level reporting (which is also broken in the uf2s in this repo).

It looks like the MAX17048 fuel gauge isn't working correctly, but I haven't had any luck figuring out why - do you happen to have any pointers / are you aware of the problem?

Cheers!

**Comment by medoix** [comment]
Fixed in b26058b
